language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
sudo: false

script:
  - npm run test-with-cov

before_deploy:
  - git remote set-url origin https://${GH_TOKEN}@github.com/ReidWeb/GitInspector-CSV
  - git  checkout -b master master
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'travis@reidweb.com'
  - git remote add push-remote https://${GH_TOKEN}@github.com/ReidWeb/GitInspector-CSV
  - npm run release
  - git log --oneline | nl -v0 | sed 's/^ \+/&HEAD~/'

deploy:
  provider: npm
  email: peter@reidweb.com
  tag: latest
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: false
    condition: '$TRAVIS_COMMIT_MESSAGE != *"chore(release)"*'
    node: 8
    repo: ReidWeb/GitInspector-CSV
    branch: master

after_deploy:
  - git log --oneline | nl -v0 | sed 's/^ \+/&HEAD~/'
  - git push --follow-tags push-remote master

after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_TOKEN ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < ./coverage/lcov.info

git:
  depth: 10
