language: node_js
node_js:
  - "7"
  - "6"
  - "4"
sudo: false

test:
  - npm run-script test-travis

after_success:
  - ls -alh
  - ./node_modules/codecov/bin/codecov -t $CODECOV_TOKEN

git:
  depth: 10