os:
  - linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  CXX=g++-4.8
language: node_js
node_js:
  - "7"
  - "6"
  - "4"
sudo: false

test:
  - npm run-script test-travis

after_success:
  - ./node_modules/codecov/bin/codecov

git:
  depth: 10