language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
sudo: false

script:
  - npm run test-with-cov

after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_TOKEN ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < ./coverage/lcov.info

git:
  depth: 10