language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.10"
  - "0.12"
sudo: false

after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_TOKEN ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < ./coverage/lcov.info

git:
  depth: 10